export const CategoryOptions = [
  {
    value: "technology",
    label: "Technology",
    subcategories: [
      "AI",
      "Web Development",
      "Mobile Development",
      "Cloud Computing",
      "DevOps",
      "Data Science",
      "Cybersecurity",
      "Blockchain",
      "Game Development",
      "UI/UX Design",
      "Software Engineering",
      "IoT",
      "AR/VR",
      "Quantum Computing",
    ],
  },
  {
    value: "business",
    label: "Business & Finance",
    subcategories: [
      "Finance",
      "Investing",
      "Marketing",
      "Sales",
      "Management",
      "Entrepreneurship",
      "Business Strategy",
      "Project Management",
      "Accounting",
      "Economics",
      "E-commerce",
      "Startups",
    ],
  },
  {
    value: "arts",
    label: "Arts & Creative",
    subcategories: [
      "Music",
      "Design",
      "Writing",
      "Film & Media",
      "Painting",
      "Photography",
      "Graphic Design",
      "Sculpture",
      "Fashion Design",
      "Animation",
      "Interior Design",
      "Creative Writing",
    ],
  },
  {
    value: "science",
    label: "Science & Research",
    subcategories: [
      "Physics",
      "Biology",
      "Chemistry",
      "Astronomy",
      "Mathematics",
      "Engineering",
      "Environmental Science",
      "Geology",
      "Research Methodology",
      "Statistics",
      "Genetics",
    ],
  },
  {
    value: "health",
    label: "Health & Wellness",
    subcategories: [
      "Yoga",
      "Fitness",
      "Medicine",
      "Nutrition",
      "Meditation",
      "Mental Health",
      "Physiotherapy",
      "Public Health",
      "Alternative Medicine",
      "Wellness Coaching",
    ],
  },
  {
    value: "personal_dev",
    label: "Personal Development & Education",
    subcategories: [
      "Leadership",
      "Study Skills",
      "Career Guidance",
      "Public Speaking",
      "Time Management",
      "Language Learning",
      "Personal Development",
      "Critical Thinking",
      "Emotional Intelligence",
      "Mindfulness",
      "Goal Setting",
    ],
  },
  {
    value: "lifestyle",
    label: "Lifestyle & Hobbies",
    subcategories: [
      "Travel",
      "Sports",
      "Gaming",
      "Fashion",
      "Cooking",
      "Gardening",
      "Photography",
      "DIY Projects",
      "Pets & Animal Care",
      "Music Instruments",
      "Crafts",
    ],
  },
  {
    value: "social_impact",
    label: "Social Impact & Volunteering",
    subcategories: [
      "Nonprofit Management",
      "Community Service",
      "Environmental Activism",
      "Social Entrepreneurship",
      "Fundraising",
      "Advocacy",
    ],
  },
  {
    value: "tech_entrepreneurship",
    label: "Tech Entrepreneurship",
    subcategories: [
      "Startup Incubation",
      "Pitching & Funding",
      "Business Models",
      "Product Management",
      "Tech Innovation",
    ],
  },
  {
    value: "languages",
    label: "Languages & Communication",
    subcategories: [
      "English",
      "Spanish",
      "French",
      "Mandarin",
      "Japanese",
      "Public Speaking",
      "Writing Skills",
      "Communication Skills",
    ],
  },
];
