export const LengthOptions = [
  { value: "5min", label: "5 minutes" },
  { value: "10min", label: "10 minutes" },
  { value: "15min", label: "15 minutes" },
  { value: "20min", label: "20 minutes" },
  { value: "25min", label: "25 minutes" },
  { value: "30min", label: "30 minutes" },
  { value: "45min", label: "45 minutes" },
  { value: "1hr", label: "1 hour" },
  { value: "1.5hr", label: "1.5 hours" },
  { value: "2hr", label: "2 hours" },
  { value: "2.5hr", label: "2.5 hours" },
  { value: "3hr", label: "3 hours" },
  { value: "3.5hr", label: "3.5 hours" },
  { value: "4hr", label: "4 hours" },
  { value: "5hr", label: "5 hours" },
  { value: "6hr", label: "6 hours" },
  { value: "7hr", label: "7 hours" },
  { value: "8hr", label: "8 hours" },
];
